### ISSUE TITLE
there was problem during run abr.py

### ISSUE THREAD

**Issue by ghost** [rsharifnasab/create_word_cloud#1]
hi,i try to run abr.py in ubuntu 18.04 but this exception occurred:
```
Traceback (most recent call last):
  File "/home/sina/.local/lib/python3.6/site-packages/PIL/Image.py", line 2082, in save
    format = EXTENSION[ext]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "abr.py", line 97, in <module>
    result_image.save(f"out/{idish}.png")
  File "/home/sina/.local/lib/python3.6/site-packages/PIL/Image.py", line 2084, in save
    raise ValueError("unknown file extension: {}".format(ext))
ValueError: unknown file extension: 
```

**Comment by rsharifnasab** [comment]
hi, i guess the problem because of the whitespace before .png in some cases, in new version i added .strip() 
please try again an inform me

**Comment by AYoonesi** [comment]
It happened in my case, too. Ubuntu 18.04
The way I fixed it:
import matplotlib.pyplot as plt
....
#result_image.save(f"{OUT_FOLDER}{user_id}.jpg")
with open(f"{OUT_FOLDER}{user_id}.txt","w") as result_file:
    result_file.write(raw_str)
with open(f"{OUT_FOLDER}cleaned_{user_id}.txt","w") as cleaned_result_file:
    cleaned_result_file.write(text)

result_image.show()

plt.imshow(word_cloud)
plt.axis('off') 
plt.savefig('out/wc1.png', dpi=1800) 
plt.close()
plt.show()
Hope it helps, did in my case lol (:

**Comment by nasirisajad** [comment]
The resulted Farsi text consists of separated characters and LTR in macOS.

**Comment by AYoonesi** [comment]
put this before print_stats(text):

from arabic_reshaper import arabic_reshaper
from bidi.algorithm import get_display
text = get_display(arabic_reshaper.reshape(text))

but install those packs first

**Comment by nasirisajad** [comment]
thanks, it works

**Comment by rsharifnasab** [comment]
thank you all for sharing this info and experaince!

**Comment by AYoonesi** [comment]
Just did it for a follow back lol (:

**Comment by nasirisajad** [comment]
Now, another problem poped up! the code didn't read the stop word lists and the final cloud includs all the stop words!

**Comment by AYoonesi** [comment]
I personally commented the first 2 stopword files
and added my own stopwords to it, based on my user in fact
Because u know persian has tons of stop words, it's not like English!

**Comment by nasirisajad** [comment]
I've added a list too, everything works fine until I used bidi.algorithm and arabic_reshaper, except the reverse Persian words! But just when I use reshaping, the code returns something like the picture:
![1398-12-15 01 23 12](https://user-images.githubusercontent.com/19924870/75926517-e986bb00-5e7f-11ea-9df6-2515bff0b2b4.jpg)

**Comment by AYoonesi** [comment]
I almost forgot! I added some more lines, too!
I'm a bit lazy!
At the end of function clean_words() def add this:
##############################
stp_words = load_stop_words()
    for stp in stp_words:
        if stp in d : return "" 
##############################
Using this I added the stop-words files

**Comment by AYoonesi** [comment]
This way worked for me

**Comment by rsharifnasab** [comment]
i added this method to utils.py and user can use it based on setting is config.py
than you all
