### ISSUE TITLE
Telegram Version Deletion

### ISSUE THREAD

**Issue by hadisfr** [rsharifnasab/create_word_cloud#4]
Hi!
Why did you remove telegram version in de07a04a5bd8b82c38b0a64bbd6a4f874416aa69 ?
It seems to work fine for me with some modification on @poyynt 's [fork](https://github.com/poyynt/abre_kalamat_bot).

**Comment by rsharifnasab** [comment]
hi 
im so sorry, i did an unsuccessful refactor and pushed it 
i'll ok it soon
